service mysql start;

mysql -e "CREATE DATABASE IF NOT EXISTS $WORDPRESS_DB_NAME";
mysql -e "CREATE USER IF NOT EXISTS '$WORDPRESS_ADMIN_USER'@'%' IDENTIFIED BY '$WORDPRESS_ADMIN_PASSWORD'";
mysql -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_ADMIN_USER'@'%'";
mysql -e "ALTER USER '$MYSQL_ROOT_USER'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';"

mysqladmin -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD shutdown;

exec mysqld