FROM debian:buster

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y mariadb-server

EXPOSE 3306

COPY ./config/my.cnf /etc/mysql/my.cnf
COPY ./config/setup.sh /tmp/mariadb-setup.sh
# COPY ./config/wp_dump.sql ./

CMD ["sh", "/tmp/mariadb-setup.sh"]