FROM debian:buster

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y mariadb-server

COPY ./config/setup.sh /tmp/setup.sh
# RUN bash /tmp/setup.sh

EXPOSE 3306

# ENTRYPOINT ["exec", "mysqld"]

