FROM debian:buster

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y mariadb-server

COPY ./config/setup.sh /tmp/setup.sh

EXPOSE 3306

ENTRYPOINT ["sh", "/tmp/setup.sh"]
