FROM debian:buster

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y \
        nginx \
        openssl

COPY ./config/nginx.conf /etc/nginx/sites-available/default

RUN openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 \
            -subj "/C=KR/ST=Seoul/O=42seoul/OU=gam" \
			-keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt

EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;"]
