FROM debian:buster

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        nginx \
        openssl

EXPOSE 443

COPY ./config/setup.sh /tmp/setup.sh
COPY ./config/nginx.conf /etc/nginx/sites-available/default

ENTRYPOINT ["sh", "/tmp/setup.sh"]