FROM debian:buster


RUN apt-get update -y && apt-get upgrade -y \
    && apt-get install -y \
        php7.3
        php-mysql
        php-fpm
        mariadb-client
        wget
        unzip

RUN wget https://ko.wordpress.org/lastest-ko_KR.zip
RUN unzip lastest-ko_KR.zip -d /var/www/
RUN chown -R  
         