FROM debian:buster

RUN sudo apt-get update -y && sudo apt-get upgrade -y \
    && sudo apt-get install wget 

RUN sudo wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php

EXPOSE 5333